"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== 环境判断与核心配置 ====================
# 关键：判断是否在 Render 生产环境（Render会设置 RENDER 环境变量）
IS_RENDER = os.environ.get('RENDER') is not None

# SECURITY WARNING: keep the secret key used in production secret!
if IS_RENDER:
    # 生产环境：从环境变量读取（你需要在Render面板设置 SECRET_KEY）
    SECRET_KEY = os.environ.get('SECRET_KEY')
    # 如果未设置，提供一个强提示
    if not SECRET_KEY:
        raise ValueError('请在Render环境变量中设置 SECRET_KEY')
else:
    # 开发环境：使用固定密钥（仅用于本地，可更改）
    SECRET_KEY = 'django-insecure-your-local-dev-key-123456-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
# 生产环境关闭DEBUG，开发环境开启
DEBUG = not IS_RENDER  # 在Render上是False，在本地是True

# 允许的主机：生产环境允许Render域名，开发环境允许本地访问
ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1', '[::1]']
# ==================== 环境判断结束 ====================

# 禁止后台CSS影响前台页面
class DisableAdminCSSMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        if not request.path.startswith('/admin/'):  # 非后台页面
            if 'text/html' in response.get('Content-Type', ''):
                content = response.content.decode()
                # 移除后台CSS链接
                import re
                content = re.sub(r'<link[^>]+/static/admin/[^>]+>', '', content)
                response.content = content.encode()
        return response

# Application definition
INSTALLED_APPS = [
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',  # 你的博客应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',  # 新增：用于在Render上高效服务静态文件
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'myblog.settings.DisableAdminCSSMiddleware',
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 判断是否在 Render 环境
IS_RENDER = os.environ.get('RENDER') is not None

if IS_RENDER:
    # Render 生产环境 - 简化可靠配置
    import dj_database_url

    # 让 dj_database_url 自动处理（Render会自动提供DATABASE_URL）
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }

    # 如果自动配置失败（返回空字典），使用SQLite作为安全回退
    if not DATABASES['default']:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'render_db.sqlite3',
            }
        }
        print("警告：使用SQLite作为生产数据库回退方案")
else:
    # 开发环境：使用本地SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'blog/static']
# 以下配置对在Render上正确收集和服务静态文件至关重要
if not DEBUG:
    # 告诉Django静态文件收集到的目录
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # 启用Whitenoise存储后端，让静态文件服务更高效
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin配置
JAZZMIN_SETTINGS = {
    "site_title": "博客管理后台",
    "site_header": "我的博客管理系统",
    "site_brand": "博客管理",
    "welcome_sign": "欢迎登录博客管理后台",
    "show_sidebar": True,
    "navigation_expanded": True,
    "theme": "darkly",  # 可选主题：darkly, flatly, slate等
}